# Generated by Django 3.2.5 on 2021-07-10 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_id', models.UUIDField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateTimeField(blank=True)),
                ('delivery_address', models.TextField()),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Closed Completed')], max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.worker')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.student')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.cafeteria')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_code', models.UUIDField()),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField()),
                ('reference_id', models.CharField(max_length=255)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.cafeteria')),
            ],
        ),
    ]
