# Generated by Django 3.2.5 on 2021-08-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
