# Generated by Django 3.2.5 on 2021-08-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210801_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='approved_by_worker',
            new_name='action_by',
        ),
    ]
