# Generated by Django 3.2.5 on 2021-07-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteriareview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'terrible'), (2, 'poor'), (3, 'good'), (4, 'very good'), (5, 'excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='menureview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'terrible'), (2, 'poor'), (3, 'good'), (4, 'very good'), (5, 'excellent')], null=True),
        ),
    ]
