# Generated by Django 3.2.5 on 2021-08-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_menu_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteria',
            name='manager',
        ),
    ]
