# Generated by Django 3.2.5 on 2021-08-01 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_cafeteria_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteriareview',
            name='cafeteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.cafeteria'),
        ),
    ]
