# Generated by Django 3.2.5 on 2021-08-01 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_worker_cafeteria'),
        ('restaurants', '0005_alter_cafeteriareview_cafeteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteriareview',
            name='reviewer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
