# Generated by Django 3.2.5 on 2021-08-08 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0007_alter_menureview_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteriareview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Terrible'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='cafeteriareview',
            name='reviewer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menureview',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Terrible'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True),
        ),
        migrations.AlterField(
            model_name='menureview',
            name='reviewer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
