# Generated by Django 3.2.5 on 2021-07-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('chef', 'Chef'), ('waiter', 'Waiter'), ('delivery', 'Delivery')], max_length=255),
        ),
    ]
