# Generated by Django 3.2.5 on 2021-07-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
