# Generated by Django 3.2.5 on 2021-08-08 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_menureview_menu'),
        ('accounts', '0004_auto_20210803_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(choices=[('Administration', 'administation'), ('Science & Technology', 'science & technology'), ('Basic Medical Sciences', 'basic medical sciences'), ('Basic Clinical Sciences', 'basic clinical sciences'), ('Health Sciences', 'health sciences'), ('Environmental Sciences', 'environmental sciences'), ('Social Sciences', 'social sciences'), ('Law', 'law'), ('Education', 'education'), ('Arts', 'arts')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'matric')},
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('user', 'worker_id', 'cafeteria')},
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=255)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='accounts.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'staff_id', 'department')},
            },
        ),
    ]
