# Generated by Django 3.2.5 on 2021-08-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210808_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
