# Generated by Django 3.2.5 on 2021-08-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_lecturer_lecturer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='lecturer_address',
            field=models.TextField(blank=True, default=str, null=True),
        ),
    ]
